jobs:
  call-build:
    permissions:
      security-events: write
    secrets:
      registry-0-psw: ${{ secrets.HUB_ACCESSS_TOKEN }}
      registry-0-usr: ${{ secrets.HUB_USERNAME }}
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: snapshot
      publish-container: ${{ github.ref == 'refs/heads/master' }}
name: Build CI
on:
  repository_dispatch:
    types: trigger-ga___ci-build.yaml
permissions: {}
