jobs:
  call-build:
    needs:
    - read-version
    permissions:
      security-events: write
    secrets:
      registry-0-psw: ${{ secrets.HUB_ACCESSS_TOKEN }}
      registry-0-usr: ${{ secrets.HUB_USERNAME }}
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: ${{ needs.read-version.outputs.version }}
      publish-container: true
  read-version:
    outputs:
      version: ${{ steps.parse.outputs.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Assert ref type
      run: "if [[ \"$GITHUB_REF_TYPE\" != \"tag\" ]]; then\n  echo \"::error::Publishing\
        \ is only supported for tags!\"\n  exit 1\nfi"
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      id: parse
      name: Parse Version from POM
      run: 'VERSION=`yq -p=xml ''.project.version'' pom.xml`

        echo "version=${VERSION}" >> $GITHUB_OUTPUT'
  update-github-release:
    needs:
    - read-version
    - call-build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      name: Download Artifacts
      uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d
      with:
        name: assembled-wars
        path: target
    - continue-on-error: true
      name: Create Checksums and SBOM
      run: 'pushd target

        echo "# SHA1" >> checksums.txt

        sha1sum dependency-track-apiserver.jar dependency-track-bundled.jar >> checksums.txt

        echo "# SHA256" >> checksums.txt

        sha256sum dependency-track-apiserver.jar dependency-track-bundled.jar >> checksums.txt

        echo "# SHA512" >> checksums.txt

        sha512sum dependency-track-apiserver.jar dependency-track-bundled.jar >> checksums.txt

        popd'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_RELEASE_TOKEN }}
      name: Update Release
      run: "cat << EOF >> .github/default-release-notes.md\n\\`\\`\\`text\n$(cat target/checksums.txt)\n\
        \\`\\`\\`\nEOF\n\ngh release view ${{ needs.read-version.outputs.version }}\
        \ \\\n  --json body --jq .body >> .github/default-release-notes.md\n\ngh release\
        \ edit ${{ needs.read-version.outputs.version }} \\\n  --notes-file \".github/default-release-notes.md\"\
        \n\ngh release upload ${{ needs.read-version.outputs.version }} \\\n  --clobber\
        \ \\\n  target/dependency-track-apiserver.jar \\\n  target/dependency-track-bundled.jar\
        \ \\\n  target/checksums.txt \\\n  target/bom.json"
name: Publish CI
on:
  repository_dispatch:
    types: trigger-ga___ci-publish.yaml
permissions: {}
