jobs:
  publish:
    if: "github.event.workflow_run.event == 'pull_request'\n  && github.event.workflow_run.conclusion\
      \ == 'success'"
    name: Report Coverage
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download PR test coverage report
      uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        name: pr-test-coverage-report
        run-id: ${{ github.event.workflow_run.id }}
    - continue-on-error: true
      name: Report Coverage to Codacy
      run: "bash <(curl -Ls https://coverage.codacy.com/get.sh) report \\\n  --project-token\
        \ ${{ secrets.CODACY_PROJECT_TOKEN }} \\\n  --commit-uuid ${{ github.event.workflow_run.head_sha\
        \ }} \\\n  --coverage-reports ./target/jacoco-ut/jacoco.xml \\\n  --language\
        \ Java"
name: Report PR Test Coverage
on:
  repository_dispatch:
    types: trigger-ga___ci-test-pr-coverage.yml
permissions: {}
